### ISSUE TITLE
How to add in the project and use it

### ISSUE THREAD

**Issue by TomYule** [Activiti/generator-jhipster-activiti#4]
How to add in the project and use it

**Comment by tuhp** [comment]
Dear all,
I'm trying to use this module but I don't know how to use it. 
Anyone show me the way to use it?

**Comment by ryandawsonuk** [comment]
Currently this project is out of date. The way to use activiti with a jhipster project right now is to first generate the jhipster project and then adding the `activiti-spring-boot-starter` dependency like the projects in https://github.com/Activiti/activiti-examples (using the [latest available version](https://search.maven.org/search?q=a:activiti-spring-boot-starter))

There then a couple of [tweaks that need to be done](https://github.com/Activiti/Activiti/issues/2009) depending what[ security/auth option you use](https://github.com/Activiti/Activiti/issues/2387). 

@salaboy is interested in improving activiti's jhipster support though so do feel free to discuss at https://gitter.im/Activiti/Activiti7

**Comment by salaboy** [comment]
@ryandawsonuk @tuhp @HaimmingYu there is a blog post coming about how to use activiti core inside jhipster app.. give me until the end of the week.

**Comment by magick93** [comment]
Thanks @salaboy - looking forward to it.

**Comment by coderLinJ5945** [comment]
Thanks @salaboy - looking forward to it.
